### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by HeadlessJoey** [pie-flavor/ArmorStandTools#1]
Firstly, thank you so much for making this!

I was able to find 2 issues by creating a very simple thing. First the head of the armorstand isn't changing when using the pumpkin item.
Nothing happens at all when that is used.

Second not so important, when in the GUI of the ingame editor there is one option to make a commandblock at your position with the exact command that spawns that armorstand. Instead it only gives the player a commandblock.
Not too important if that doesn't work but the head thing is a problem.

**Comment by pie-flavor** [comment]
The command block is intentional. If you place it it will have the command inside it.
